# Generated by Django 2.0 on 2018-10-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20181009_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '用户课程', 'verbose_name_plural': '用户课程'},
        ),
    ]
